import os 

SECRET_KEY = ""
JWT_SECRET_KEY = ""

DB_USER = ""
DB_PASSWORD = ""
DB_HOST = ""
DB_NAME = ""

SQLALCHEMY_DATABASE_URI = f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}/{DB_NAME}"
SQLALCHEMY_TRACK_MODIFICATIONS = False